USE [CIS655_Shah_N]
GO

/****** Object:  Table [dbo].[BRINGS_T]    Script Date: 5/16/2016 8:37:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BRINGS_T](
	[PlaintiffID] [int] NOT NULL,
	[CaseID] [int] NOT NULL,
	[RequestedJudgment] [decimal](18, 0) NULL,
	[Type] [nvarchar](20) NULL,
 CONSTRAINT [PK_BRINGS_T] PRIMARY KEY CLUSTERED 
(
	[PlaintiffID] ASC,
	[CaseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BRINGS_T]  WITH CHECK ADD  CONSTRAINT [FK_BRINGS_T_BRINGS_T] FOREIGN KEY([PlaintiffID])
REFERENCES [dbo].[PLAINTIFF_T] ([PlaintiffID])
GO

ALTER TABLE [dbo].[BRINGS_T] CHECK CONSTRAINT [FK_BRINGS_T_BRINGS_T]
GO

ALTER TABLE [dbo].[BRINGS_T]  WITH CHECK ADD  CONSTRAINT [FK_BRINGS_T_CASE_T] FOREIGN KEY([CaseID])
REFERENCES [dbo].[CASE_T] ([CaseID])
GO

ALTER TABLE [dbo].[BRINGS_T] CHECK CONSTRAINT [FK_BRINGS_T_CASE_T]
GO

