USE [CIS655_Shah_N]
GO

/****** Object:  Table [dbo].[CHARGES HISTORY_T]    Script Date: 5/16/2016 8:37:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CHARGES HISTORY_T](
	[ChargesID] [int] NOT NULL,
	[DefendantID] [int] NOT NULL,
	[Punishment] [nvarchar](30) NULL,
	[isImprisoned] [bit] NULL,
 CONSTRAINT [PK_CHARGES HISTORY_T] PRIMARY KEY CLUSTERED 
(
	[ChargesID] ASC,
	[DefendantID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CHARGES HISTORY_T]  WITH CHECK ADD  CONSTRAINT [FK_CHARGES HISTORY_T_CHARGES_T] FOREIGN KEY([ChargesID])
REFERENCES [dbo].[CHARGES_T] ([ChargesID])
GO

ALTER TABLE [dbo].[CHARGES HISTORY_T] CHECK CONSTRAINT [FK_CHARGES HISTORY_T_CHARGES_T]
GO

ALTER TABLE [dbo].[CHARGES HISTORY_T]  WITH CHECK ADD  CONSTRAINT [FK_CHARGES HISTORY_T_DEFENDANT_T] FOREIGN KEY([DefendantID])
REFERENCES [dbo].[DEFENDANT_T] ([DefendantID])
GO

ALTER TABLE [dbo].[CHARGES HISTORY_T] CHECK CONSTRAINT [FK_CHARGES HISTORY_T_DEFENDANT_T]
GO

