USE [CIS655_Shah_N]
GO

/****** Object:  Table [dbo].[COURT_T]    Script Date: 5/16/2016 8:39:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COURT_T](
	[CourtID] [int] NOT NULL,
	[JudgeID] [int] NULL,
	[Name] [nvarchar](35) NOT NULL,
	[Address] [nvarchar](30) NOT NULL,
	[County] [nchar](10) NOT NULL,
	[State] [nchar](2) NOT NULL,
	[Room] [int] NULL,
 CONSTRAINT [PK_COURT_T] PRIMARY KEY CLUSTERED 
(
	[CourtID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[COURT_T]  WITH CHECK ADD  CONSTRAINT [FK_COURT_T_JUDGE_T] FOREIGN KEY([JudgeID])
REFERENCES [dbo].[JUDGE_T] ([JudgeID])
GO

ALTER TABLE [dbo].[COURT_T] CHECK CONSTRAINT [FK_COURT_T_JUDGE_T]
GO

