USE [CIS655_Shah_N]
GO

/****** Object:  Table [dbo].[DEFENDS_T]    Script Date: 5/16/2016 8:40:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEFENDS_T](
	[DefendantID] [int] NOT NULL,
	[CaseID] [int] NOT NULL,
	[Reason] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_DEFENDS_T] PRIMARY KEY CLUSTERED 
(
	[DefendantID] ASC,
	[CaseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[DEFENDS_T]  WITH CHECK ADD  CONSTRAINT [FK_DEFENDS_T_CASE_T] FOREIGN KEY([CaseID])
REFERENCES [dbo].[CASE_T] ([CaseID])
GO

ALTER TABLE [dbo].[DEFENDS_T] CHECK CONSTRAINT [FK_DEFENDS_T_CASE_T]
GO

ALTER TABLE [dbo].[DEFENDS_T]  WITH CHECK ADD  CONSTRAINT [FK_DEFENDS_T_DEFENDANT_T] FOREIGN KEY([DefendantID])
REFERENCES [dbo].[DEFENDANT_T] ([DefendantID])
GO

ALTER TABLE [dbo].[DEFENDS_T] CHECK CONSTRAINT [FK_DEFENDS_T_DEFENDANT_T]
GO

