USE [CIS655_Shah_N]
GO

/****** Object:  Table [dbo].[EXPERT_T]    Script Date: 5/16/2016 8:40:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EXPERT_T](
	[ExpertID] [int] NOT NULL,
	[Area] [nvarchar](35) NOT NULL,
 CONSTRAINT [PK_EXPERT_T] PRIMARY KEY CLUSTERED 
(
	[ExpertID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[EXPERT_T]  WITH CHECK ADD  CONSTRAINT [FK_EXPERT_T_LEGALENTITY_T] FOREIGN KEY([ExpertID])
REFERENCES [dbo].[LEGALENTITY_T] ([EntityID])
GO

ALTER TABLE [dbo].[EXPERT_T] CHECK CONSTRAINT [FK_EXPERT_T_LEGALENTITY_T]
GO

