USE [CIS655_Shah_N]
GO

/****** Object:  Table [dbo].[HEARS_T]    Script Date: 5/16/2016 8:40:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HEARS_T](
	[CaseID] [int] NOT NULL,
	[CourtID] [int] NOT NULL,
	[Date] [date] NOT NULL,
	[Judgment] [nchar](1) NULL,
	[JudgeID] [int] NOT NULL,
 CONSTRAINT [PK_HEARS_T] PRIMARY KEY CLUSTERED 
(
	[CaseID] ASC,
	[CourtID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[HEARS_T]  WITH CHECK ADD  CONSTRAINT [FK_HEARS_T_CASE_T] FOREIGN KEY([CaseID])
REFERENCES [dbo].[CASE_T] ([CaseID])
GO

ALTER TABLE [dbo].[HEARS_T] CHECK CONSTRAINT [FK_HEARS_T_CASE_T]
GO

ALTER TABLE [dbo].[HEARS_T]  WITH CHECK ADD  CONSTRAINT [FK_HEARS_T_COURT_T] FOREIGN KEY([CourtID])
REFERENCES [dbo].[COURT_T] ([CourtID])
GO

ALTER TABLE [dbo].[HEARS_T] CHECK CONSTRAINT [FK_HEARS_T_COURT_T]
GO

ALTER TABLE [dbo].[HEARS_T]  WITH CHECK ADD  CONSTRAINT [FK_HEARS_T_JUDGE_T] FOREIGN KEY([CaseID])
REFERENCES [dbo].[JUDGE_T] ([JudgeID])
GO

ALTER TABLE [dbo].[HEARS_T] CHECK CONSTRAINT [FK_HEARS_T_JUDGE_T]
GO

