USE [CIS655_Shah_N]
GO

/****** Object:  Table [dbo].[JUDGE_T]    Script Date: 5/16/2016 8:40:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[JUDGE_T](
	[JudgeID] [int] NOT NULL,
	[Type] [char](10) NOT NULL,
	[YearsServed] [decimal](18, 0) NOT NULL,
 CONSTRAINT [PK_JUDGE_T] PRIMARY KEY CLUSTERED 
(
	[JudgeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[JUDGE_T]  WITH CHECK ADD  CONSTRAINT [FK_JUDGE_T_LEGALENTITY_T] FOREIGN KEY([JudgeID])
REFERENCES [dbo].[LEGALENTITY_T] ([EntityID])
GO

ALTER TABLE [dbo].[JUDGE_T] CHECK CONSTRAINT [FK_JUDGE_T_LEGALENTITY_T]
GO

