USE [CIS655_Shah_N]
GO

/****** Object:  Table [dbo].[LEGALENTITY_T]    Script Date: 5/16/2016 8:41:14 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LEGALENTITY_T](
	[EntityID] [int] NOT NULL,
	[Address] [nvarchar](50) NOT NULL,
	[City] [nvarchar](15) NOT NULL,
	[State] [nchar](2) NOT NULL,
	[PostalCode] [int] NOT NULL,
	[Country] [nvarchar](15) NOT NULL,
	[PrimaryPhone] [int] NULL,
	[OptionalPhone] [int] NULL,
	[Email] [nvarchar](25) NULL,
	[ClientType] [nchar](1) NULL,
	[NetWorth] [decimal](18, 0) NULL,
 CONSTRAINT [PK_LEGALENTITY_T] PRIMARY KEY CLUSTERED 
(
	[EntityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[LEGALENTITY_T]  WITH CHECK ADD  CONSTRAINT [CK_LEGALENTITY_T_CLIENTTYPE] CHECK  (([ClientType]='O' OR [ClientType]='P'))
GO

ALTER TABLE [dbo].[LEGALENTITY_T] CHECK CONSTRAINT [CK_LEGALENTITY_T_CLIENTTYPE]
GO

ALTER TABLE [dbo].[LEGALENTITY_T]  WITH CHECK ADD  CONSTRAINT [CK_LEGALENTITY_T_EMAIL] CHECK  (([Email] like '%@%'))
GO

ALTER TABLE [dbo].[LEGALENTITY_T] CHECK CONSTRAINT [CK_LEGALENTITY_T_EMAIL]
GO

