USE [CIS655_Shah_N]
GO

/****** Object:  Table [dbo].[ORGANIZATION_T]    Script Date: 5/16/2016 8:41:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ORGANIZATION_T](
	[OrgID] [int] NOT NULL,
	[Name] [nvarchar](35) NOT NULL,
	[ContactName] [nvarchar](35) NULL,
 CONSTRAINT [PK_ORGANIZATION_T] PRIMARY KEY CLUSTERED 
(
	[OrgID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ORGANIZATION_T]  WITH CHECK ADD  CONSTRAINT [FK_ORGANIZATION_T_LEGALENTITY_T] FOREIGN KEY([OrgID])
REFERENCES [dbo].[LEGALENTITY_T] ([EntityID])
GO

ALTER TABLE [dbo].[ORGANIZATION_T] CHECK CONSTRAINT [FK_ORGANIZATION_T_LEGALENTITY_T]
GO

