USE [CIS655_Shah_N]
GO

/****** Object:  Table [dbo].[PERSON_T]    Script Date: 5/16/2016 8:41:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERSON_T](
	[PersonID] [int] NOT NULL,
	[FirstName] [nvarchar](15) NOT NULL,
	[LastName] [nchar](10) NOT NULL,
	[DateOfBirth] [date] NOT NULL,
	[Gender] [nchar](1) NULL,
 CONSTRAINT [PK_PERSON_T] PRIMARY KEY CLUSTERED 
(
	[PersonID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PERSON_T]  WITH CHECK ADD  CONSTRAINT [FK_PERSON_T_LEGALENTITY_T] FOREIGN KEY([PersonID])
REFERENCES [dbo].[LEGALENTITY_T] ([EntityID])
GO

ALTER TABLE [dbo].[PERSON_T] CHECK CONSTRAINT [FK_PERSON_T_LEGALENTITY_T]
GO

