USE [CIS655_Shah_N]
GO

/****** Object:  Table [dbo].[PLAINTIFF_T]    Script Date: 5/16/2016 8:41:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PLAINTIFF_T](
	[PlaintiffID] [int] NOT NULL,
	[Profession] [nvarchar](35) NOT NULL,
 CONSTRAINT [PK_PLAINTIFF_T] PRIMARY KEY CLUSTERED 
(
	[PlaintiffID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PLAINTIFF_T]  WITH CHECK ADD  CONSTRAINT [FK_PLAINTIFF_T_LEGALENTITY_T] FOREIGN KEY([PlaintiffID])
REFERENCES [dbo].[LEGALENTITY_T] ([EntityID])
GO

ALTER TABLE [dbo].[PLAINTIFF_T] CHECK CONSTRAINT [FK_PLAINTIFF_T_LEGALENTITY_T]
GO

