USE [CIS655_Shah_N]
GO

/****** Object:  Table [dbo].[SPECIALITY SET_T]    Script Date: 5/16/2016 8:42:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SPECIALITY SET_T](
	[SpecialityID] [int] NOT NULL,
	[LawyerID] [int] NOT NULL,
 CONSTRAINT [PK_SPECIALITY SET_1] PRIMARY KEY CLUSTERED 
(
	[SpecialityID] ASC,
	[LawyerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SPECIALITY SET_T]  WITH CHECK ADD  CONSTRAINT [FK_SPECIALITY SET_T_LAWYER_T] FOREIGN KEY([LawyerID])
REFERENCES [dbo].[LAWYER_T] ([LawyerID])
GO

ALTER TABLE [dbo].[SPECIALITY SET_T] CHECK CONSTRAINT [FK_SPECIALITY SET_T_LAWYER_T]
GO

ALTER TABLE [dbo].[SPECIALITY SET_T]  WITH CHECK ADD  CONSTRAINT [FK_SPECIALITY SET_T_SPECIALITY_T] FOREIGN KEY([SpecialityID])
REFERENCES [dbo].[SPECIALITY_T] ([SpecialityID])
GO

ALTER TABLE [dbo].[SPECIALITY SET_T] CHECK CONSTRAINT [FK_SPECIALITY SET_T_SPECIALITY_T]
GO

