USE [CIS655_Shah_N]
GO

/****** Object:  Table [dbo].[STUDIES_T]    Script Date: 5/16/2016 8:42:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STUDIES_T](
	[ExpertID] [int] NOT NULL,
	[CaseID] [int] NOT NULL,
	[Date] [date] NOT NULL,
	[Hours] [decimal](18, 0) NOT NULL,
 CONSTRAINT [PK_STUDIES_T] PRIMARY KEY CLUSTERED 
(
	[ExpertID] ASC,
	[CaseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[STUDIES_T]  WITH CHECK ADD  CONSTRAINT [FK_STUDIES_T_CASE_T] FOREIGN KEY([CaseID])
REFERENCES [dbo].[CASE_T] ([CaseID])
GO

ALTER TABLE [dbo].[STUDIES_T] CHECK CONSTRAINT [FK_STUDIES_T_CASE_T]
GO

ALTER TABLE [dbo].[STUDIES_T]  WITH CHECK ADD  CONSTRAINT [FK_STUDIES_T_EXPERT_T] FOREIGN KEY([ExpertID])
REFERENCES [dbo].[EXPERT_T] ([ExpertID])
GO

ALTER TABLE [dbo].[STUDIES_T] CHECK CONSTRAINT [FK_STUDIES_T_EXPERT_T]
GO

